from cloudvolume import CloudVolume
import subprocess
import argparse
import math

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Run max downsample on all blocks in parallel")
    parser.add_argument("--input_path", type=str, help="Path to the input CloudVolume")
    parser.add_argument("--out_mip", type=int, help="MIP level for the output downsampled data")
    parser.add_argument("--output_dir", type=str, help="Directory to save the output blocks")
    parser.add_argument("--block_size", type=int, help="Size of the blocks to process in parallel")
    parser.add_argument("--max_processes", type=int, help="Maximum number of parallel processes to run")
    #parser.add_argument("--stride", type=int, default=1, help="Stride to use when iterating over blocks, in units of output voxels")
    args = parser.parse_args()

    out_shape = tuple(CloudVolume(args.input_path, mip=args.out_mip).shape[0:3])
    in_shape = tuple(CloudVolume(args.input_path, mip=0).shape[0:3])

    resolution = CloudVolume(args.input_path, mip=args.out_mip).scales[0]['resolution']
    chunk_sizes = [[1024//(2**args.out_mip), 1024//(2**args.out_mip), 1024//(2**args.out_mip)]]
    stride = math.ceil(1024 / args.block_size) + 1

    volume_info = {
            "type": "segmentation",
            "layer_type": "segmentation",
            "data_type": "uint64",
            "num_channels": 1,
            "scales": [
                {
                    "voxel_offset": [0, 0, 0],
                    "key": "0_0_0",
                    "size": out_shape,
                    "resolution": resolution,
                    "chunk_sizes": chunk_sizes,
                    "encoding": "compressed_segmentation",
                    "compressed_segmentation_block_size": [8, 8, 8],
                }
            ]
        }

    out_vol = CloudVolume(args.output_dir, info=volume_info, bounded=False, progress=True, non_aligned_writes=False, parallel=1)
    out_vol.provenance.description = f"Max downsampled semantic segmentation generated by Pi2/Monai UNet model"
    out_vol.provenance.owners = ["jonas.hemesath@bi.mpg.de"]
    out_vol.commit_info()
    out_vol.commit_provenance()

    steps = [math.ceil(in_shape[i] / (args.block_size)) for i in range(3)]

    total_jobs = steps[0] * steps[1] * steps[2]
    print(f"Launching {total_jobs} jobs to max downsample the whole volume...")

    processes = []
    process_id = 0
    for x_i in range(stride):
        for y_i in range(stride):
            for z_i in range(stride):
                for x in range(x_i, steps[0], stride):
                    for y in range(y_i, steps[1], stride):
                        for z in range(z_i, steps[2], stride):
                            xb0_hr = x * args.block_size
                            yb0_hr = y * args.block_size
                            zb0_hr = z * args.block_size

                            xb1_hr = min(xb0_hr + args.block_size, in_shape[0])
                            yb1_hr = min(yb0_hr + args.block_size, in_shape[1])
                            zb1_hr = min(zb0_hr + args.block_size, in_shape[2])

                            xb0_lr = xb0_hr // (2 ** args.out_mip)
                            yb0_lr = yb0_hr // (2 ** args.out_mip)
                            zb0_lr = zb0_hr // (2 ** args.out_mip)

                            xb1_lr = min(xb0_lr + args.block_size // (2 ** args.out_mip), out_shape[0])
                            yb1_lr = min(yb0_lr + args.block_size // (2 ** args.out_mip), out_shape[1])
                            zb1_lr = min(zb0_lr + args.block_size // (2 ** args.out_mip), out_shape[2])

                            processes.append(subprocess.Popen(["srun", "--time=7-0", "--gres=gpu:a40:1", "--mem=400000", "--tasks", "1", "--cpus-per-task", "32", "--nice", "python", "/cajal/nvmescratch/users/johem/esrf_data_conversion/segmentation/max_downsample/max_downsample.py", 
                                                                "--input_path", args.input_path, 
                                                                "--output_dir", args.output_dir, 
                                                                "--input_mip", "0", 
                                                                "--output_mip", str(args.out_mip), 
                                                                "--block_shape_hr", str(xb1_hr - xb0_hr), str(yb1_hr - yb0_hr), str(zb1_hr - zb0_hr), 
                                                                "--block_org_hr", str(xb0_hr), str(yb0_hr), str(zb0_hr), 
                                                                "--block_shape_lr", str(xb1_lr - xb0_lr), str(yb1_lr - yb0_lr), str(zb1_lr - zb0_lr), 
                                                                "--block_org_lr", str(xb0_lr), str(yb0_lr), str(zb0_lr)],
                                                            stdout=subprocess.PIPE, stderr=subprocess.PIPE))
                            process_id += 1
                            if len(processes) >= args.max_processes:
                                for i, process in enumerate(processes):
                                    outs, errs = process.communicate()
                                    if errs:
                                        print(f"Process {i+1} errors:")
                                        print(errs.decode('utf-8') if isinstance(errs, bytes) else errs)
                                    if outs:
                                        print(f"Process {i+1} output:")
                                        print(outs.decode('utf-8') if isinstance(outs, bytes) else outs)
                                    print('Process', i+1, 'of', len(processes), 'done')
                                    print('Total jobs submitted', process_id, 'of', total_jobs)
                                processes = []
                if len(processes) > 0:
                    for i, process in enumerate(processes):
                        outs, errs = process.communicate()
                        if errs:
                            print(f"Process {i+1} errors:")
                            print(errs.decode('utf-8') if isinstance(errs, bytes) else errs)
                        if outs:
                            print(f"Process {i+1} output:")
                            print(outs.decode('utf-8') if isinstance(outs, bytes) else outs)
                        print('Process', i+1, 'of', len(processes), 'done')
                        print('Total jobs submitted', process_id, 'of', total_jobs)
