from cloudvolume import CloudVolume
import subprocess
import argparse
import math

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--brain_regions_path", type=str, help="Path to the brain regions CloudVolume")
    parser.add_argument("--BV_path", type=str, help="Path to the BV CloudVolume")
    parser.add_argument("--brain_regions_mip", type=int, help="MIP level of the brain regions data")
    parser.add_argument("--num_processes", type=int, help="Number of processes to use for parallel processing")
    parser.add_argument("--output_file", type=str, help="Path to the output file")
    parser.add_argument("--block_size", type=int, default=1024, help="Size of the blocks to process in parallel")
    args = parser.parse_args()


    brain_regions_vol = CloudVolume(args.brain_regions_path, mip=0)
    BV_vol = CloudVolume(args.BV_path, mip=0)

    block_size_hr = args.block_size
    block_size_lr = block_size_hr // (2 ** args.brain_regions_mip)

    out_shape = tuple(BV_vol.shape[0:3])

    volume_info = {
            "type": "segmentation",
            "layer_type": "segmentation",
            "data_type": "uint64",
            "num_channels": 1,
            "scales": [
                {
                    "voxel_offset": [0, 0, 0],
                    "key": "0_0_0",
                    "size": out_shape,
                    "resolution": [727.8, 727.8, 727.8],     # Resolution in nm
                    "chunk_sizes": [[1024, 1024, 1024]],
                    "encoding": "compressed_segmentation",
                    "compressed_segmentation_block_size": [8, 8, 8],
                }
            ]
        }

    out_vol = CloudVolume(args.output_file, info=volume_info, bounded=False, progress=True, non_aligned_writes=False, parallel=1)
    out_vol.provenance.description = f"Semantic segmentation of BV filtered by brain regions generated by Pi2/Monai UNet model"
    out_vol.provenance.owners = ["jonas.hemesath@bi.mpg.de"]
    out_vol.commit_info()
    out_vol.commit_provenance()

    steps = [math.ceil(out_shape[i] / block_size_hr) for i in range(3)]

    total_jobs = steps[0] * steps[1] * steps[2]
    print(f"Launching {total_jobs} jobs to label the BV by brain region...")
    processes = []
    for x in range(steps[0]):
        for y in range(steps[1]):
            for z in range(steps[2]):
                x0_hr = x * block_size_hr
                y0_hr = y * block_size_hr
                z0_hr = z * block_size_hr

                x1_hr = min((x + 1) * block_size_hr, out_shape[0])
                y1_hr = min((y + 1) * block_size_hr, out_shape[1])
                z1_hr = min((z + 1) * block_size_hr, out_shape[2])


                processes.append(subprocess.Popen(["python", "label_BV_by_brain_region.py", 
                                                    "--brain_regions_path", args.brain_regions_path, 
                                                    "--BV_path", args.BV_path, 
                                                    "--brain_regions_mip", str(args.brain_regions_mip), 
                                                    "--block_org_hr", str(x0_hr), str(y0_hr), str(z0_hr), 
                                                    "--block_shape_hr", str(x1_hr - x0_hr), str(y1_hr - y0_hr), str(z1_hr - z0_hr), 
                                                    "--output_file", args.output_file], stdout=subprocess.PIPE, stderr=subprocess.PIPE))

