from cloudvolume import CloudVolume
import argparse

parser = argparse.ArgumentParser(description="Generate test volumes for BV testing")
parser.add_argument("--BV_path", type=str, help="Path to the BV file")
parser.add_argument("--output_path", type=str, help="Path to the output volume")
parser.add_argument("--block_shape", nargs=3, type=int, default=[1024, 1024, 1024], help="Shape of the block to generate")
parser.add_argument("--origins", nargs='+', type=int, help="List of origins for the blocks to generate, in the format 'x,y,z x,y,z ...'")
args = parser.parse_args()

if __name__ == "__main__":
    bv_vol = CloudVolume(args.BV_path, progress=True)
    for origin in args.origins:
        x, y, z = map(int, origin.split(','))
        block_shape = args.block_shape
        block = bv_vol[x:x+block_shape[0], y:y+block_shape[1], z:z+block_shape[2]]

        volume_info = {
                "type": "segmentation",
                "layer_type": "segmentation",
                "data_type": "uint64",
                "num_channels": 1,
                "scales": [
                    {
                        "voxel_offset": [0, 0, 0],
                        "key": "0_0_0",
                        "size": args.block_shape,
                        "resolution": [727.8, 727.8, 727.8],     # Resolution in nm
                        "chunk_sizes": [[1024, 1024, 1024]],
                        "encoding": "compressed_segmentation",
                        "compressed_segmentation_block_size": [8, 8, 8],
                    }
                ]
            }

        out_vol = CloudVolume(args.output_path + f"/block_{x}_{y}_{z}", info=volume_info, bounded=False, progress=True, non_aligned_writes=False, parallel=1)
        out_vol.provenance.description = f"Test volume - Semantic segmentation generated by Pi2/Monai UNet model"
        out_vol.provenance.owners = ["jonas.hemesath@bi.mpg.de"]
        out_vol.commit_info()
        out_vol.commit_provenance()

        out_vol[0:block_shape[0], 0:block_shape[1], 0:block_shape[2]] = block